package GUI;

import java.awt.CardLayout;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Lance
 * @editor Katecory
 */
public final class GroceryStore extends javax.swing.JFrame
{
    public static final String MAIN_MENU_PANEL_CARDNAME = "MainMenuCard";
    public static final String STAFF_MANAGEMENT_PANEL_CARDNAME = "StaffManagementCard";
    public static final String ITEM_MANAGEMENT_PANEL_CARDNAME = "ItemManagementCard";
    
    private StaffManagementPanel staffManagementPanel;
    private ItemManagementPanel itemManagementPanel;
    
    /**
     * Creates new form GroceryStore
     */
    public GroceryStore() throws SQLException, ClassNotFoundException
    {
        // Auto generated method
        initComponents();
        
        // Custom method
        initCustomFields();
    }
    
    private void initCustomFields() throws ClassNotFoundException, SQLException
    {
        this.staffManagementPanel = new StaffManagementPanel(MotherPanel);
        this.itemManagementPanel = new ItemManagementPanel(MotherPanel);
        addChildrenPanelToLayout();
    }
    
    private void addChildrenPanelToLayout()
    {
        MotherPanel.add(this.staffManagementPanel, STAFF_MANAGEMENT_PANEL_CARDNAME);
        MotherPanel.add(this.itemManagementPanel, ITEM_MANAGEMENT_PANEL_CARDNAME);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MotherPanel = new javax.swing.JPanel();
        MainMenuPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Staff_Button = new javax.swing.JButton();
        About_Button = new javax.swing.JButton();
        Exit_Button = new javax.swing.JButton();
        Item_Button1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MotherPanel.setLayout(new java.awt.CardLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 50)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Grocery Store Management");

        Staff_Button.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Staff_Button.setText("Staff");
        Staff_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_ButtonActionPerformed(evt);
            }
        });

        About_Button.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        About_Button.setText("About");
        About_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                About_ButtonActionPerformed(evt);
            }
        });

        Exit_Button.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Exit_Button.setText("Exit");
        Exit_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit_ButtonActionPerformed(evt);
            }
        });

        Item_Button1.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        Item_Button1.setText("Item");
        Item_Button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MainMenuPanelLayout = new javax.swing.GroupLayout(MainMenuPanel);
        MainMenuPanel.setLayout(MainMenuPanelLayout);
        MainMenuPanelLayout.setHorizontalGroup(
            MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1006, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainMenuPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Staff_Button, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(Item_Button1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(About_Button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Exit_Button, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(387, 387, 387))
        );
        MainMenuPanelLayout.setVerticalGroup(
            MainMenuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainMenuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Staff_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Item_Button1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(About_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Exit_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(200, Short.MAX_VALUE))
        );

        MotherPanel.add(MainMenuPanel, "MainMenuCard");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MotherPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(MotherPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Staff_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_ButtonActionPerformed
        CardLayout layout = (CardLayout) MotherPanel.getLayout();
        layout.show(MotherPanel, GroceryStore.STAFF_MANAGEMENT_PANEL_CARDNAME);
    }//GEN-LAST:event_Staff_ButtonActionPerformed

    private void About_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_About_ButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_About_ButtonActionPerformed

    private void Exit_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit_ButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_Exit_ButtonActionPerformed

    private void Item_Button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Button1ActionPerformed
        CardLayout layout = (CardLayout) MotherPanel.getLayout();
        layout.show(MotherPanel, GroceryStore.ITEM_MANAGEMENT_PANEL_CARDNAME);
    }//GEN-LAST:event_Item_Button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroceryStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroceryStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroceryStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroceryStore.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GroceryStore().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(GroceryStore.class.getName()).log(Level.SEVERE, null, ex);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(GroceryStore.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton About_Button;
    private javax.swing.JButton Exit_Button;
    private javax.swing.JButton Item_Button1;
    private javax.swing.JPanel MainMenuPanel;
    private javax.swing.JPanel MotherPanel;
    private javax.swing.JButton Staff_Button;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
