package GUI;

import Database.DBItemHandler;
import Item.*;

import java.awt.CardLayout;
import java.awt.Container;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dongz
 * @Editor Katecory
 */
public class ItemManagementPanel extends javax.swing.JPanel
{
    private Container parent;
    private TableRenderer tableRenderer;
    private ItemList itemList;
    private boolean isEditMode = false;
    
    private DBItemHandler dbItemHandler;

    /**
     * Creates new form StaffManagementPanel
     * @param parent The parent component
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public ItemManagementPanel(Container parent) throws ClassNotFoundException, SQLException
    {
        initComponents();
        
        initCustomFields(parent);
        initItemData();
    }
    
    private void initCustomFields(Container parent)
    {
        this.parent = parent;
        this.dbItemHandler = new DBItemHandler();
        this.tableRenderer = new TableRenderer();
        this.itemList = null;
    }
    
    private void initItemData() throws ClassNotFoundException, SQLException
    {
        this.itemList = this.dbItemHandler.getFullDataFromDBForItemList();
        DefaultTableModel tableModel = (DefaultTableModel) Item_Table.getModel();
        tableRenderer.renderToTable(tableModel, itemList.getItem());
    }
    
    private void DisplayItemList()
    {
        DefaultTableModel tableModel = (DefaultTableModel) Item_Table.getModel();
        tableRenderer.renderToTable(tableModel, itemList.getItem());
    }
    
    private void fillItemToForm(Item item)
    {
        isEditMode = true;
        String stringImprice = Integer.toString(item.getImprice());
        String strinSellprice = Integer.toString(item.getSelprice()) ;
        String stringQuantity = Integer.toString(item.getQuantity()) ;
        ID_Textfield.setText(item.getId());
        Name_Textfield.setText(item.getName());
        Type_Textfield.setText(item.getType());
        Imprice_Textfield.setText(stringImprice);
        Sellprice_Textfield.setText(strinSellprice);
        Quantity_Textfield.setText(stringQuantity);
    }
    
    private void CleanForm()
    {
        ID_Textfield.setText("");
        Name_Textfield.setText("");
        Type_Textfield.setText("");
        Imprice_Textfield.setText("");
        Sellprice_Textfield.setText("");
        Quantity_Textfield.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Staff_Management_heading = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        Item_Table = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Quantity_Textfield = new javax.swing.JTextField();
        ID_Textfield = new javax.swing.JTextField();
        Name_Textfield = new javax.swing.JTextField();
        Type_Textfield = new javax.swing.JTextField();
        Imprice_Textfield = new javax.swing.JTextField();
        Sellprice_Textfield = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Button_Panel = new javax.swing.JPanel();
        Item_Save_Button = new javax.swing.JButton();
        Item_Add_Button = new javax.swing.JButton();
        Item_Change_Button = new javax.swing.JButton();
        Item_Refresh_Button = new javax.swing.JButton();
        Item_Delete_Button = new javax.swing.JButton();
        Item_Find_Button = new javax.swing.JButton();
        Item_Mainmenu_Button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        Staff_Management_heading.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        Staff_Management_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Staff_Management_heading.setText("Item Management");

        Item_Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Type", "Imprice", "Sellprice", "Quantity"
            }
        ));
        Item_Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Item_TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Item_Table);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Item Info:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("Type:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("Imprice:");

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("Name:");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("Sellprice:");

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("Quantity:");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel8.setText("ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Type_Textfield))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ID_Textfield))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Name_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Imprice_Textfield)
                    .addComponent(Sellprice_Textfield)
                    .addComponent(Quantity_Textfield))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Imprice_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sellprice_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Type_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Quantity_Textfield, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Item_Save_Button.setText("Save");
        Item_Save_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Save_ButtonActionPerformed(evt);
            }
        });

        Item_Add_Button.setText("Add");
        Item_Add_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Add_ButtonActionPerformed(evt);
            }
        });

        Item_Change_Button.setText("Change");
        Item_Change_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Change_ButtonActionPerformed(evt);
            }
        });

        Item_Refresh_Button.setText("Refresh");
        Item_Refresh_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Refresh_ButtonActionPerformed(evt);
            }
        });

        Item_Delete_Button.setText("Delete");
        Item_Delete_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Delete_ButtonActionPerformed(evt);
            }
        });

        Item_Find_Button.setText("Find");
        Item_Find_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Find_ButtonActionPerformed(evt);
            }
        });

        Item_Mainmenu_Button.setText("Main Menu");
        Item_Mainmenu_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Item_Mainmenu_ButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Button_PanelLayout = new javax.swing.GroupLayout(Button_Panel);
        Button_Panel.setLayout(Button_PanelLayout);
        Button_PanelLayout.setHorizontalGroup(
            Button_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button_PanelLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(Item_Add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item_Change_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item_Save_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item_Delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item_Find_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item_Refresh_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Item_Mainmenu_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        Button_PanelLayout.setVerticalGroup(
            Button_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Button_PanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(Button_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Item_Add_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item_Change_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item_Save_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item_Delete_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item_Find_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item_Refresh_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item_Mainmenu_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jLabel2.setText("To update a staff please first type in the ID and find him in the table, change the variable and then lastly click on change button or you can click on the table");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(Staff_Management_heading, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1)))
                    .addComponent(Button_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Staff_Management_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Item_Save_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Save_ButtonActionPerformed
        try
        {
            this.dbItemHandler.insertIntoItemListToDB(itemList);
        }
        catch (ClassNotFoundException ex)
        {
            Logger.getLogger(ItemManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex)
        {
            Logger.getLogger(ItemManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        try
        {
            this.dbItemHandler.deleteItemInDBFromItemList(itemList);
        }
        catch (ClassNotFoundException ex)
        {
            Logger.getLogger(ItemManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex)
        {
            Logger.getLogger(ItemManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        Item_Refresh_ButtonActionPerformed(evt);
    }//GEN-LAST:event_Item_Save_ButtonActionPerformed

    private void Item_Add_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Add_ButtonActionPerformed
        //Get item and get data
        Item item = new Item();
        item.setId(ID_Textfield.getText());
        item.setName(Name_Textfield.getText());
        item.setType(Type_Textfield.getText());
        item.setImprice(Integer.parseInt(Imprice_Textfield.getText()));
        item.setSelprice(Integer.parseInt(Sellprice_Textfield.getText()));
        item.setQuantity(Integer.parseInt(Quantity_Textfield.getText()));
        
        //Check duplicate
        Item existedItem = itemList.FindByID(item.getId());
        if (existedItem != null)
        {
            JOptionPane.showMessageDialog(this, "The ID has been used");
        }
        else
        {
            itemList.add(item);
        }
        
        DisplayItemList();
        CleanForm();
    }//GEN-LAST:event_Item_Add_ButtonActionPerformed

    private void Item_Change_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Change_ButtonActionPerformed
        try
        {
            Item item = new Item();
            item.setId(ID_Textfield.getText());
            item.setName(Name_Textfield.getText());
            item.setType(Type_Textfield.getText());
            item.setImprice(Integer.parseInt(Imprice_Textfield.getText()));
            item.setSelprice(Integer.parseInt(Sellprice_Textfield.getText()));
            item.setQuantity(Integer.parseInt(Quantity_Textfield.getText()));
            
            if (isEditMode == true)
            {
                if(itemList.FindByID(item.getId()) == null)
                {
                    JOptionPane.showMessageDialog(this, "Staff ID is not existed");
                    return;
                }
                itemList.updateItem(item);
            }
            else
            {
                if(itemList.FindByID(item.getId()) != null)
                {
                    JOptionPane.showMessageDialog(this, "Staff ID is existed and can't insert new employee, if you want to update you must first type the id and find it in the table,change variable and save again  ");
                    return;
                }
                itemList.add(item);
            }
            
            DisplayItemList();
            CleanForm();
        }catch (HeadlessException e){
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_Item_Change_ButtonActionPerformed

    private void Item_Refresh_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Refresh_ButtonActionPerformed
        try
        {
            initItemData();
        } 
        catch (ClassNotFoundException ex)
        {
            Logger.getLogger(ItemManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex)
        {
            Logger.getLogger(ItemManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        CleanForm();
        isEditMode = false;
    }//GEN-LAST:event_Item_Refresh_ButtonActionPerformed

    private void Item_Delete_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Delete_ButtonActionPerformed
         try
        {
            boolean isDeleted = itemList.DeleteByID(ID_Textfield.getText());
            if(isDeleted)
            {
                JOptionPane.showMessageDialog(this, "Item deleted");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "The Item ID is not existed or the data is error");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        DisplayItemList();
        CleanForm();
    }//GEN-LAST:event_Item_Delete_ButtonActionPerformed

    private void Item_Find_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Find_ButtonActionPerformed
        try
        {
            Item item = itemList.FindByID(ID_Textfield.getText());
            
            if(item != null)
            {
                fillItemToForm(item);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "The item ID is not existed ");}    
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_Item_Find_ButtonActionPerformed

    private void Item_Mainmenu_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Item_Mainmenu_ButtonActionPerformed
        CardLayout layout = (CardLayout) parent.getLayout();
        layout.show(parent, GroceryStore.MAIN_MENU_PANEL_CARDNAME);
    }//GEN-LAST:event_Item_Mainmenu_ButtonActionPerformed

    private void Item_TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Item_TableMouseClicked
        int row = Item_Table.getSelectedRow();
        if (row >= 0)
        {
            String itemID = (String) Item_Table.getValueAt(row, 0);
            Item item = itemList.FindByID(itemID);
            if(item != null)
            {
                fillItemToForm(item);
            }
        }
    }//GEN-LAST:event_Item_TableMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Button_Panel;
    private javax.swing.JTextField ID_Textfield;
    private javax.swing.JTextField Imprice_Textfield;
    private javax.swing.JButton Item_Add_Button;
    private javax.swing.JButton Item_Change_Button;
    private javax.swing.JButton Item_Delete_Button;
    private javax.swing.JButton Item_Find_Button;
    private javax.swing.JButton Item_Mainmenu_Button;
    private javax.swing.JButton Item_Refresh_Button;
    private javax.swing.JButton Item_Save_Button;
    private javax.swing.JTable Item_Table;
    private javax.swing.JTextField Name_Textfield;
    private javax.swing.JTextField Quantity_Textfield;
    private javax.swing.JTextField Sellprice_Textfield;
    private javax.swing.JLabel Staff_Management_heading;
    private javax.swing.JTextField Type_Textfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    // End of variables declaration//GEN-END:variables
}
