package GUI;

import Database.DBStaffHandler;
import Staff.*;

import java.awt.CardLayout;
import java.awt.Container;
import java.awt.HeadlessException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Katecory
 */
public class StaffManagementPanel extends javax.swing.JPanel
{
    private Container parent;
    private TableRenderer tableRenderer;
    private StaffList staffList;
    private boolean isEditMode = false;
    
    private DBStaffHandler dbStaffHandler;

    /**
     * Creates new form StaffManagementPanel
     * @param parent The parent component
     * @throws java.lang.ClassNotFoundException
     * @throws java.sql.SQLException
     */
    public StaffManagementPanel(Container parent) throws ClassNotFoundException, SQLException
    {
        initComponents();
        
        initCustomFields(parent);
        initStaffData();
    }
    
    private void initCustomFields(Container parent) {
        this.parent = parent;
        this.dbStaffHandler = new DBStaffHandler();
        this.tableRenderer = new TableRenderer();
        this.staffList = null;
    }
    
    private void initStaffData() throws ClassNotFoundException, SQLException
    {
        this.staffList = this.dbStaffHandler.getFullDataFromDBForStaffList();
        DefaultTableModel tableModel = (DefaultTableModel) Staff_table_table.getModel();
        tableRenderer.renderToTable(tableModel, staffList.getStaffs());
    }
    
    private void DisplayStaffList()
    {
        DefaultTableModel tableModel = (DefaultTableModel) Staff_table_table.getModel();
        tableRenderer.renderToTable(tableModel, staffList.getStaffs());
    }
    
    private void fillStaffToForm(Staff staff)
    {
        isEditMode = true;
        Name_TextField.setText(staff.GetName());
        Role_TextField.setText(staff.GetRole());
        PhoneNum_TextField.setText(staff.GetPhoneNum());
        ID_TextField.setText(staff.GetID());
    }
    
    private void CleanForm()
    {
        ID_TextField.setText("");
        Name_TextField.setText("");
        Role_TextField.setText("");
        PhoneNum_TextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Staff_Management_heading = new javax.swing.JLabel();
        Staff_Info_Panel = new javax.swing.JPanel();
        ID_Label = new javax.swing.JLabel();
        Name_Lable = new javax.swing.JLabel();
        Role_Label = new javax.swing.JLabel();
        PhoneNum_Label = new javax.swing.JLabel();
        ID_TextField = new javax.swing.JTextField();
        Name_TextField = new javax.swing.JTextField();
        Role_TextField = new javax.swing.JTextField();
        PhoneNum_TextField = new javax.swing.JTextField();
        Staff_Button_Panel = new javax.swing.JPanel();
        Staff_add_button = new javax.swing.JButton();
        Staff_save_button = new javax.swing.JButton();
        Staff_delete_button = new javax.swing.JButton();
        Staff_find_button = new javax.swing.JButton();
        Staff_refresh_table_button = new javax.swing.JButton();
        Staff_change_button = new javax.swing.JButton();
        The_line_below_staff_management = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Staff_panel_hold_table = new javax.swing.JPanel();
        Back_to_Main_Menu_in_Staff_Management_Button = new javax.swing.JButton();
        Staff_table_ScrollPanel = new javax.swing.JScrollPane();
        Staff_table_table = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(997, 688));

        Staff_Management_heading.setFont(new java.awt.Font("Arial", 0, 40)); // NOI18N
        Staff_Management_heading.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Staff_Management_heading.setText("Staff Management");

        ID_Label.setText("ID");

        Name_Lable.setText("Phone Num");

        Role_Label.setText("Name");

        PhoneNum_Label.setText("Role");

        javax.swing.GroupLayout Staff_Info_PanelLayout = new javax.swing.GroupLayout(Staff_Info_Panel);
        Staff_Info_Panel.setLayout(Staff_Info_PanelLayout);
        Staff_Info_PanelLayout.setHorizontalGroup(
            Staff_Info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Staff_Info_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Staff_Info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Staff_Info_PanelLayout.createSequentialGroup()
                        .addComponent(ID_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ID_TextField, javax.swing.GroupLayout.DEFAULT_SIZE, 665, Short.MAX_VALUE))
                    .addGroup(Staff_Info_PanelLayout.createSequentialGroup()
                        .addComponent(Role_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Name_TextField))
                    .addGroup(Staff_Info_PanelLayout.createSequentialGroup()
                        .addComponent(Name_Lable, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PhoneNum_TextField))
                    .addGroup(Staff_Info_PanelLayout.createSequentialGroup()
                        .addComponent(PhoneNum_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Role_TextField)))
                .addContainerGap())
        );
        Staff_Info_PanelLayout.setVerticalGroup(
            Staff_Info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Staff_Info_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Staff_Info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ID_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ID_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Staff_Info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Role_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Staff_Info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PhoneNum_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Role_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Staff_Info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name_Lable, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PhoneNum_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        Staff_Button_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));

        Staff_add_button.setText("Add");
        Staff_add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_add_buttonActionPerformed(evt);
            }
        });

        Staff_save_button.setText("Save");
        Staff_save_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_save_buttonActionPerformed(evt);
            }
        });

        Staff_delete_button.setText("Delete");
        Staff_delete_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_delete_buttonActionPerformed(evt);
            }
        });

        Staff_find_button.setText("Find");
        Staff_find_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_find_buttonActionPerformed(evt);
            }
        });

        Staff_refresh_table_button.setText("Refresh");
        Staff_refresh_table_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_refresh_table_buttonActionPerformed(evt);
            }
        });

        Staff_change_button.setText("Change");
        Staff_change_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Staff_change_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Staff_Button_PanelLayout = new javax.swing.GroupLayout(Staff_Button_Panel);
        Staff_Button_Panel.setLayout(Staff_Button_PanelLayout);
        Staff_Button_PanelLayout.setHorizontalGroup(
            Staff_Button_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Staff_Button_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(Staff_Button_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Staff_refresh_table_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Staff_change_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Staff_add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Staff_save_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Staff_delete_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Staff_find_button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(59, 59, 59))
        );
        Staff_Button_PanelLayout.setVerticalGroup(
            Staff_Button_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Staff_Button_PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Staff_add_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Staff_change_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Staff_save_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Staff_delete_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Staff_find_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Staff_refresh_table_button)
                .addContainerGap())
        );

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("To update a staff please first type in the ID and find him in the table, change the variable and then lastly click on change button or you can click on the table");

        javax.swing.GroupLayout Staff_panel_hold_tableLayout = new javax.swing.GroupLayout(Staff_panel_hold_table);
        Staff_panel_hold_table.setLayout(Staff_panel_hold_tableLayout);
        Staff_panel_hold_tableLayout.setHorizontalGroup(
            Staff_panel_hold_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 978, Short.MAX_VALUE)
        );
        Staff_panel_hold_tableLayout.setVerticalGroup(
            Staff_panel_hold_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        Back_to_Main_Menu_in_Staff_Management_Button.setText("Main Menu");
        Back_to_Main_Menu_in_Staff_Management_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Back_to_Main_Menu_in_Staff_Management_ButtonActionPerformed(evt);
            }
        });

        Staff_table_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Role", "Phone Num"
            }
        ));
        Staff_table_table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Staff_table_tableMouseClicked(evt);
            }
        });
        Staff_table_ScrollPanel.setViewportView(Staff_table_table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Staff_Info_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Staff_Button_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(4, 4, 4))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Back_to_Main_Menu_in_Staff_Management_Button, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Staff_table_ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 985, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(The_line_below_staff_management)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(Staff_panel_hold_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(Staff_Management_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 975, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Staff_Info_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Staff_Button_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Staff_table_ScrollPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Back_to_Main_Menu_in_Staff_Management_Button)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Staff_Management_heading, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(The_line_below_staff_management, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 295, Short.MAX_VALUE)
                    .addComponent(Staff_panel_hold_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(62, 62, 62)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Staff_refresh_table_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_refresh_table_buttonActionPerformed
        try 
        {
            initStaffData();
        } 
        catch (ClassNotFoundException | SQLException ex) 
        {
            Logger.getLogger(StaffManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        CleanForm();
        isEditMode = false;
    }//GEN-LAST:event_Staff_refresh_table_buttonActionPerformed

    private void Back_to_Main_Menu_in_Staff_Management_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Back_to_Main_Menu_in_Staff_Management_ButtonActionPerformed
        CardLayout layout = (CardLayout) parent.getLayout();
        layout.show(parent, GroceryStore.MAIN_MENU_PANEL_CARDNAME);
    }//GEN-LAST:event_Back_to_Main_Menu_in_Staff_Management_ButtonActionPerformed

    private void Staff_delete_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_delete_buttonActionPerformed
        try
        {
            boolean isDeleted = staffList.DeleteByID(ID_TextField.getText());
            if(isDeleted)
            {
                JOptionPane.showMessageDialog(this, "Staff deleted");
            }
            else
            {
                JOptionPane.showMessageDialog(this, "The staff ID is not existed or the data is error");
            }
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        DisplayStaffList();
        CleanForm();
    }//GEN-LAST:event_Staff_delete_buttonActionPerformed

    private void Staff_add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_add_buttonActionPerformed
        //Get staff and get data
        Staff staff = new Staff();
        staff.SetID(ID_TextField.getText());
        staff.SetName(Name_TextField.getText());
        staff.SetRole(Role_TextField.getText());
        staff.SetPhoneNum(PhoneNum_TextField.getText());
        
        //Check duplicate
        Staff existedStaff = staffList.FindByID(staff.GetID());
        if (existedStaff != null)
        {
            JOptionPane.showMessageDialog(this, "The ID has been used");
        }
        else
        {
            staffList.Add(staff);
        }
        DisplayStaffList();
        CleanForm();
    }//GEN-LAST:event_Staff_add_buttonActionPerformed

    private void Staff_find_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_find_buttonActionPerformed
        try
        {
            Staff staff = staffList.FindByID(ID_TextField.getText());
            
            if(staff != null)
            {
                fillStaffToForm(staff);
            }
            else
            {
                JOptionPane.showMessageDialog(this, "The staff ID is not existed ");}    
        }
        catch (Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_Staff_find_buttonActionPerformed

    private void Staff_table_tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Staff_table_tableMouseClicked
        int row = Staff_table_table.getSelectedRow();
        if (row >= 0)
        {
            String staffID = (String) Staff_table_table.getValueAt(row, 0);
            Staff staff = staffList.FindByID(staffID);
            if(staff != null)
            {
                fillStaffToForm(staff);
            }
        }
    }//GEN-LAST:event_Staff_table_tableMouseClicked

    private void Staff_change_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_change_buttonActionPerformed
        try
        {
            Staff staff = new Staff();
            staff.SetID(ID_TextField.getText());
            staff.SetName(Name_TextField.getText());
            staff.SetRole(Role_TextField.getText());
            staff.SetPhoneNum(PhoneNum_TextField.getText());
            
            if (isEditMode == true)
            {
                if(staffList.FindByID(staff.GetID()) == null)
                {
                    JOptionPane.showMessageDialog(this, "Staff ID is not existed");
                    return;
                }

                staffList.updateStaff(staff);
            }
            else
            {
                if(staffList.FindByID(staff.GetID()) != null)
                {
                    JOptionPane.showMessageDialog(this, "Staff ID is existed and can't insert new employee, if you want to update you must first type the id and find it in the table,change variable and save again  ");
                    return;
                }
                staffList.Add(staff);
            }
            
            DisplayStaffList();
            CleanForm();
        }catch (HeadlessException e){
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_Staff_change_buttonActionPerformed

    private void Staff_save_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Staff_save_buttonActionPerformed
        try 
        {
            this.dbStaffHandler.insertIntoStaffListToDB(staffList);
        } 
        catch (ClassNotFoundException | SQLException ex) 
        {
            Logger.getLogger(StaffManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        try 
        {
            this.dbStaffHandler.deleteStaffInDBFromStaffList(staffList);
        } 
        catch (ClassNotFoundException | SQLException ex) 
        {
            Logger.getLogger(StaffManagementPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        Staff_refresh_table_buttonActionPerformed(evt);
    }//GEN-LAST:event_Staff_save_buttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Back_to_Main_Menu_in_Staff_Management_Button;
    private javax.swing.JLabel ID_Label;
    private javax.swing.JTextField ID_TextField;
    private javax.swing.JLabel Name_Lable;
    private javax.swing.JTextField Name_TextField;
    private javax.swing.JLabel PhoneNum_Label;
    private javax.swing.JTextField PhoneNum_TextField;
    private javax.swing.JLabel Role_Label;
    private javax.swing.JTextField Role_TextField;
    private javax.swing.JPanel Staff_Button_Panel;
    private javax.swing.JPanel Staff_Info_Panel;
    private javax.swing.JLabel Staff_Management_heading;
    private javax.swing.JButton Staff_add_button;
    private javax.swing.JButton Staff_change_button;
    private javax.swing.JButton Staff_delete_button;
    private javax.swing.JButton Staff_find_button;
    private javax.swing.JPanel Staff_panel_hold_table;
    private javax.swing.JButton Staff_refresh_table_button;
    private javax.swing.JButton Staff_save_button;
    private javax.swing.JScrollPane Staff_table_ScrollPanel;
    private javax.swing.JTable Staff_table_table;
    private javax.swing.JSeparator The_line_below_staff_management;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
